API_URL = "http://67.205.168.129:8080/"

api_login = API_URL + "user/login"
api_logout = API_URL + "user/logout"
api_registration = API_URL + "user/register"
api_get_photos = API_URL + "user/pictures"
api_upload = API_URL + "picture/upload"
api_photo_view = API_URL + "picture/"
api_album_create = API_URL + "album"
api_album = API_URL + "album"
api_create_tag = API_URL + "picture/tags"
